In [2]:
%matplotlib inline
from __future__ import division, print_function
import sys, os
sys.path.append('/global/common/edison/contrib/hpcosmo/hpcports_gnu-default/fitsio-0.9.10_c0563e28-9.0/lib/python2.7/site-packages/')
import numpy as np
import matplotlib.pyplot as plt
import fitsio

In [3]:
data_dir = '/project/projectdirs/desi/target/analysis/truth_dr3.1_match_only/'

filelist = [
            'decals_dr3.1_cfhtls-d2-i_match_only', 
            'decals_dr3.1_cfhtls-d2-r_match_only', 
            'decals_dr3.1_cosmos_acs_match_only', 
            'decals_dr3.1_stripe82_stars_match_only', 
            'decals_dr3.1_spies_match_only', 
            'decals_dr3.1_deep2-field2_match_only', 
            'decals_dr3.1_deep2-field3_match_only', 
            'decals_dr3.1_deep2-field4_match_only', 
            'decals_dr3.1_cosmos_zphot_match_only', 
            'decals_dr3.1_vipers_pdr2_w1_match_only', 
            'decals_dr3.1_vipers_pdr2_w4_match_only',
            'decals_dr3.1_ages_match_only', 
            'decals_dr3.1_stripe82_specz_match_only', 
            'decals_dr3.1_sdss_match_only', 
            'decals_dr3.1_AllQSO.DECaLS.dr2_match_only', 
            'decals_dr3.1_Stars_str82_355_4.DECaLS.dr2_match_only',
        ]
catalogs = [filelist[i][:-11] for i in range(len(filelist))]

In [4]:
filename = 'decals_dr3.1_deep2-field2_match_only'
print(filename)
cat = fitsio.read(os.path.join(data_dir, filename)+'.fits', columns=['DECAM_NOBS', 'DECAM_DEPTH', 'DECAM_GALDEPTH'])
# mask = (cat['DECAM_NOBS'][:, 1]>=3) & (cat['DECAM_NOBS'][:, 2]>=3) & (cat['DECAM_NOBS'][:, 4]>=3)
mask = (cat['DECAM_NOBS'][:, 1]>=2) & (cat['DECAM_NOBS'][:, 2]>=2) & (cat['DECAM_NOBS'][:, 4]>=2)
cat = cat[mask]
print(len(cat))
mask = (cat['DECAM_DEPTH'][:, 1]>0) & (cat['DECAM_DEPTH'][:, 2]>0) & (cat['DECAM_DEPTH'][:, 4]>0)
print(np.sum(~mask))
cat = cat[mask]
mask = (cat['DECAM_GALDEPTH'][:, 1]>0) & (cat['DECAM_GALDEPTH'][:, 2]>0) & (cat['DECAM_GALDEPTH'][:, 4]>0)
print(np.sum(~mask))
cat = cat[mask]

decals_dr3.1_deep2-field2_match_only
6559
0
0


In [5]:
print(np.mean(cat['DECAM_NOBS'][:, 1]))
print(np.mean(cat['DECAM_NOBS'][:, 2]))
print(np.mean(cat['DECAM_NOBS'][:, 4]))
print(np.mean(-2.5*(np.log10((5/np.sqrt(cat['DECAM_GALDEPTH'][:, 1])))-9)))
print(np.mean(-2.5*(np.log10((5/np.sqrt(cat['DECAM_GALDEPTH'][:, 2])))-9)))
print(np.mean(-2.5*(np.log10((5/np.sqrt(cat['DECAM_GALDEPTH'][:, 4])))-9)))

2.64003659094
2.64323829852
2.64308583626
23.9608
23.5684
22.3918


In [6]:
nobs = np.zeros([len(filelist), 3])
galdepth_median = np.zeros([len(filelist), 3])
galdepth_mean = np.zeros([len(filelist), 3])
galdepth_std = np.zeros([len(filelist), 3])
depth_median = np.zeros([len(filelist), 3])
depth_mean = np.zeros([len(filelist), 3])
depth_std = np.zeros([len(filelist), 3])

for index, filename in enumerate(filelist):
    print(catalogs[index])
    cat = fitsio.read(os.path.join(data_dir, filename)+'.fits', columns=['DECAM_NOBS', 'DECAM_DEPTH', 'DECAM_GALDEPTH'])
    # mask = (cat['DECAM_NOBS'][:, 1]>=3) & (cat['DECAM_NOBS'][:, 2]>=3) & (cat['DECAM_NOBS'][:, 4]>=3)
    mask1 = (cat['DECAM_NOBS'][:, 1]>=2) & (cat['DECAM_NOBS'][:, 2]>=2) & (cat['DECAM_NOBS'][:, 4]>=2)
    mask2 = (cat['DECAM_DEPTH'][:, 1]>0) & (cat['DECAM_DEPTH'][:, 2]>0) & (cat['DECAM_DEPTH'][:, 4]>0)
    mask3 = (cat['DECAM_GALDEPTH'][:, 1]>0) & (cat['DECAM_GALDEPTH'][:, 2]>0) & (cat['DECAM_GALDEPTH'][:, 4]>0)
    print(len(cat), np.sum(mask1 & (~mask2)), np.sum((mask1 & mask2) & (~mask3)))
    cat = cat[(mask1 & mask2 & mask3)]
    
    nobs[index, 0] = np.mean(cat['DECAM_NOBS'][:, 1])
    nobs[index, 1] = np.mean(cat['DECAM_NOBS'][:, 2])
    nobs[index, 2] = np.mean(cat['DECAM_NOBS'][:, 4])

    galdepth_median[index, 0] = np.median(-2.5*(np.log10((5/np.sqrt(cat['DECAM_GALDEPTH'][:, 1])))-9))
    galdepth_median[index, 1] = np.median(-2.5*(np.log10((5/np.sqrt(cat['DECAM_GALDEPTH'][:, 2])))-9))
    galdepth_median[index, 2] = np.median(-2.5*(np.log10((5/np.sqrt(cat['DECAM_GALDEPTH'][:, 4])))-9))
    galdepth_mean[index, 0] = np.mean(-2.5*(np.log10((5/np.sqrt(cat['DECAM_GALDEPTH'][:, 1])))-9))
    galdepth_mean[index, 1] = np.mean(-2.5*(np.log10((5/np.sqrt(cat['DECAM_GALDEPTH'][:, 2])))-9))
    galdepth_mean[index, 2] = np.mean(-2.5*(np.log10((5/np.sqrt(cat['DECAM_GALDEPTH'][:, 4])))-9))
    galdepth_std[index, 0] = np.std(-2.5*(np.log10((5/np.sqrt(cat['DECAM_GALDEPTH'][:, 1])))-9))
    galdepth_std[index, 1] = np.std(-2.5*(np.log10((5/np.sqrt(cat['DECAM_GALDEPTH'][:, 2])))-9))
    galdepth_std[index, 2] = np.std(-2.5*(np.log10((5/np.sqrt(cat['DECAM_GALDEPTH'][:, 4])))-9))

    depth_median[index, 0] = np.median(-2.5*(np.log10((5/np.sqrt(cat['DECAM_DEPTH'][:, 1])))-9))
    depth_median[index, 1] = np.median(-2.5*(np.log10((5/np.sqrt(cat['DECAM_DEPTH'][:, 2])))-9))
    depth_median[index, 2] = np.median(-2.5*(np.log10((5/np.sqrt(cat['DECAM_DEPTH'][:, 4])))-9))
    depth_mean[index, 0] = np.mean(-2.5*(np.log10((5/np.sqrt(cat['DECAM_DEPTH'][:, 1])))-9))
    depth_mean[index, 1] = np.mean(-2.5*(np.log10((5/np.sqrt(cat['DECAM_DEPTH'][:, 2])))-9))
    depth_mean[index, 2] = np.mean(-2.5*(np.log10((5/np.sqrt(cat['DECAM_DEPTH'][:, 4])))-9))
    depth_std[index, 0] = np.std(-2.5*(np.log10((5/np.sqrt(cat['DECAM_DEPTH'][:, 1])))-9))
    depth_std[index, 1] = np.std(-2.5*(np.log10((5/np.sqrt(cat['DECAM_DEPTH'][:, 2])))-9))
    depth_std[index, 2] = np.std(-2.5*(np.log10((5/np.sqrt(cat['DECAM_DEPTH'][:, 4])))-9))

decals_dr3.1_cfhtls-d2-i
79356 192 0
decals_dr3.1_cfhtls-d2-r
78439 195 0
decals_dr3.1_cosmos_acs
134816 297 0
decals_dr3.1_stripe82_stars
1146258 33826 0
decals_dr3.1_spies
1570817 8957 0
decals_dr3.1_deep2-field2
6925 0 0
decals_dr3.1_deep2-field3
11259 0 0
decals_dr3.1_deep2-field4
10100 4 0
decals_dr3.1_cosmos_zphot
194756 432 0
decals_dr3.1_vipers_pdr2_w1
58957 636 0
decals_dr3.1_vipers_pdr2_w4
29004 8 0
decals_dr3.1_ages
30963 37 0
decals_dr3.1_stripe82_specz
181511 2278 0
decals_dr3.1_sdss
2093440 4571 0
decals_dr3.1_AllQSO.DECaLS.dr2
67788 33 0
decals_dr3.1_Stars_str82_355_4.DECaLS.dr2
78213 329 0


In [ ]:
# Number of visits
for index, catalog in enumerate(catalogs):
    print(catalog)
    print(nobs[index])

In [28]:
# Depth
for index, catalog in enumerate(catalogs):
    print(catalog)
    print(galdepth_median[index])

decals_dr3.1_cfhtls-d2-i
[ 24.42068863  23.93570709  23.37114716]
decals_dr3.1_cfhtls-d2-r
[ 24.42086029  23.9366684   23.37169838]
decals_dr3.1_cosmos_acs
[ 24.41353989  23.92997932  23.37798882]
decals_dr3.1_stripe82_stars
[ 24.59356308  24.29403687  23.12832642]
decals_dr3.1_spies
[ 24.71281052  24.28126907  23.18947601]
decals_dr3.1_deep2-field2
[ 24.01736259  23.6423893   22.46056747]
decals_dr3.1_deep2-field3
[ 24.72844124  24.36789322  23.27338028]
decals_dr3.1_deep2-field4
[ 24.53479958  24.22894287  22.92362022]
decals_dr3.1_cosmos_zphot
[ 24.39672661  23.9246521   23.3788147 ]
decals_dr3.1_vipers_pdr2_w1
[ 24.55582047  24.19566345  23.00593567]
decals_dr3.1_vipers_pdr2_w4
[ 24.56409454  24.24456024  23.15581131]
decals_dr3.1_ages
[ 23.75779152  23.40780258  22.48681068]
decals_dr3.1_stripe82_specz
[ 24.55744171  24.23284149  23.06515312]
decals_dr3.1_sdss
[ 24.33402061  23.98722839  22.91981506]
decals_dr3.1_AllQSO.DECaLS.dr2
[ 24.30500221  23.92745018  22.99544716]
decals_dr

In [108]:
nobs

array([[  6.79596529,   4.86793073,  10.56619886],
       [  6.80289611,   4.8736117 ,  10.58219905],
       [  6.79552416,   4.8445948 ,  10.7789368 ],
       [  5.24750976,   4.0472119 ,   3.68100005],
       [  7.47371622,   4.4656127 ,   4.0916871 ],
       [  2.64003659,   2.6432383 ,   2.64308584],
       [  6.93381593,   4.4582119 ,   3.02923757],
       [  4.62010152,   3.24527919,   3.31736041],
       [  6.62186617,   4.74379939,  10.62520892],
       [  4.57602979,   3.78267392,   4.32940517],
       [  4.20173983,   3.03192682,   2.97376799],
       [  3.41751437,   3.41707209,   3.47456877],
       [  5.29450734,   3.96627967,   3.69097737],
       [  3.96640991,   3.57125806,   3.67918587],
       [  4.12195044,   3.55837951,   3.81288617],
       [  7.66200503,   4.40635677,   4.15119852]])

In [31]:
galdepth_median

array([[ 24.42068863,  23.93570709,  23.37114716],
       [ 24.42086029,  23.9366684 ,  23.37169838],
       [ 24.41353989,  23.92997932,  23.37798882],
       [ 24.59356308,  24.29403687,  23.12832642],
       [ 24.71281052,  24.28126907,  23.18947601],
       [ 24.01736259,  23.6423893 ,  22.46056747],
       [ 24.72844124,  24.36789322,  23.27338028],
       [ 24.53479958,  24.22894287,  22.92362022],
       [ 24.39672661,  23.9246521 ,  23.3788147 ],
       [ 24.55582047,  24.19566345,  23.00593567],
       [ 24.56409454,  24.24456024,  23.15581131],
       [ 23.75779152,  23.40780258,  22.48681068],
       [ 24.55744171,  24.23284149,  23.06515312],
       [ 24.33402061,  23.98722839,  22.91981506],
       [ 24.30500221,  23.92745018,  22.99544716],
       [ 24.68061066,  24.24944687,  23.13567734]])

In [32]:
np.savetxt('./nobs.txt', nobs)
np.savetxt('./galdepth_median.txt', galdepth_median)
np.savetxt('./galdepth_mean.txt', galdepth_mean)
np.savetxt('./galdepth_std.txt', galdepth_std)
np.savetxt('./depth_median.txt', depth_median)
np.savetxt('./depth_mean.txt', depth_mean)
np.savetxt('./depth_std.txt', depth_std)

In [7]:
galdepth_median - depth_median

array([[-0.26895905, -0.30364227, -0.22707748],
       [-0.26878738, -0.30305099, -0.22686958],
       [-0.26444626, -0.30292511, -0.22612572],
       [-0.22657394, -0.34913445, -0.40046692],
       [-0.20311165, -0.32678986, -0.39347458],
       [-0.17115593, -0.21221924, -0.24026871],
       [-0.20570564, -0.34286118, -0.43839264],
       [-0.26427841, -0.38881493, -0.38651848],
       [-0.25987816, -0.29527283, -0.22679901],
       [-0.25733376, -0.33499336, -0.35225868],
       [-0.24660492, -0.32832718, -0.37771606],
       [-0.16970444, -0.21420479, -0.22705269],
       [-0.22046089, -0.33836746, -0.38029671],
       [-0.23907661, -0.3118763 , -0.3486557 ],
       [-0.24038506, -0.30365562, -0.35589409],
       [-0.20132256, -0.31443787, -0.36819077]])